services:

  caddy:
    image: caddy:2
    hostname: caddy.myhpi.local
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config:/etc/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./log:/log
    networks:
      - default

networks:
  default:
    name: default-network
    external: true

volumes:
  caddy_data:
  caddy_config:
