services:

  slackbot:
    image: registry.gitlab.hpi.de/fachschaftsrat/fsr-bot:main
    restart: unless-stopped
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - slackbot_db:/home/node/app/data
      - ./config.json:/home/node/app/config.json:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  slackbot_db:
