services:

  generator:
    image: registry.gitlab.hpi.de/fachschaftsrat/bewirtungsnachweis-generator
    hostname: bewirtung.myhpi.local
    restart: unless-stopped
    volumes:
      - ./catering-templates.json:/app/catering-templates.json:ro
    networks:
      - default

networks:
  default:
    name: default-network
    external: true
