services:

  engelsystem:
    image: ghcr.io/fsr-de/engelsystem
    hostname: engelsystem.myhpi.local
    env_file: .env
    networks:
      - database
      - internet
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.2
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
      - monitoring
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    hostname: pma.engelsystem.myhpi.local
    environment:
      PMA_HOST: db
    networks:
      - database
      - internet
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db: {}

networks:
  database:
    internal: true
  internet:
    name: default-network
    external: true
  monitoring:
    name: monitoring
    external: true
